name: physarum_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-348.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  physarum_cpp_ffi:
    path: physarum_cpp_ffi/

  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  theme_tailor_annotation: ^1.0.3

  proxima_logger: ^0.6.3
  intl: ^0.17.0
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.2
  
  flutter_riverpod: ^2.3.0
  go_router: ^6.5.1
  chopper: ^6.1.1

  url_launcher: ^6.1.10
  rive: ^0.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_native_splash: ^2.2.19

  app_runner: ^2.1.2
  package_info_plus: ^3.1.0
  flutter_dotenv: ^5.0.2
  appmetrica_plugin: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  lints: ^2.0.1

  freezed: ^2.3.2
  json_serializable: ^6.6.1
  theme_tailor: ^1.0.8

  build_runner:
  flutter_gen_runner:
  chopper_generator: ^6.0.0
  flutter_launcher_icons: ^0.13.1

  custom_lint:
  riverpod_lint:
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true